### ISSUE TITLE
How to use the SDK in PHP

### ISSUE THREAD

**Issue by gren83** [SwedbankPay/swedbank-pay-sdk-php#26]
Hi,

Maybe a stupid question but if I want to use this in PHP, on the web server, is there any information or example on how to do that? All I see in the SDK is classes so I figured I should have a PHP-file where I call the classes depending on what operations I want to do, obviously. But what file do I require to start the SDK? I have no autoload.php since I just downloaded this in a zip-file and then uploaded to our web server. I am not familiar with composer, git or unit testing and such, I just want to use this SDK on a web site to integrate Swedbank Pay.

Is there any example-PHP-file? And yes I see that there is a tests-folder but this is supposed to be run via unittest i guess so it doesn't really help.

Or maybe I am completely on the wrong track here?

Thanks in advance!

**Comment by asbjornu** [comment]
Hi and thanks for reaching out! Sorry for the lack of documentation. The SDK is still in an early stage and documentation will come, there's just a few more pressing issues being dealt with. Just check back in a few weeks and documentation on how to use the SDK should be in place for sure.

**Comment by gren83** [comment]
Hi @asbjornu,
Thanks for your response. Then I will check back here in a few weeks. 
If someone happens to have a PHP-script that shows how to initialize the SDK before that it would be great! Maybe it can be posted here in that case.

**Comment by olegisk** [comment]
@gren83 You can check tests/ directory. There're good examples of the code.

**Comment by gren83** [comment]
@olegisk Thanks for the response. I tried to run tests/ConsumerTest.php but I can't seem to get it to work when calling it from the web. I think I probably need to have some require_once at the top of the file but I can't get it right it seems.

**Comment by aait** [comment]
@gren83 How do you run tests? I should run using follow commands:
```
composer install
 vendor/bin/phpunit --configuration=./tests/phpunit.xml --bootstrap=./tests/bootstrap.php ./tests/ --coverage-clover=coverage.xml
```

**Comment by mattiashallstrom** [comment]
It's unfortunate to see that this SDK still has no documentation and also are missing functionality that are available in swedbankpay.

**Comment by aait** [comment]
@mattiashallstrom Which functionality are missing?
Regarding documentation you can check `/tests/` directory. There are tests whick you can use as example.

**Comment by mattiashallstrom** [comment]
@aait the thing I remember at the moment is a way to set paymentpurchase to generate recurrencetoken: "PaymentPurchase->setGenerateRecurrenceToken(true)".

Also I would had prefered more work on the actual part that we users use to use the SDK.
Your code is beautifully created and structured, but harder for a user to implement. I have read the test cases and have done a full implementation. I might miss some parts, but I would prefer not to have to all below just to do a paymentpurchase:

`$payeeInfo = new PaymentPayeeInfo();
        $payeeInfo->setPayeeId($this->payee_id)
            ->setPayeeReference($payeeReference)
            ->setPayeeName('Ballou')
            ->setOrderReference($invoiceId);

        $price = new PriceItem();
        $price->setType('Creditcard')
            ->setAmount(round($amountInclVat * 100))
            ->setVatAmount(round($amountVat * 100));

        $prices = new PricesCollection();
        $prices->addItem($price);

        $creditCard = new PaymentPurchaseCreditcard();
        $creditCard->setNo3DSecure(false)
            ->setMailOrderTelephoneOrder(false)
            ->setRejectCardNot3DSecureEnrolled(false)
            ->setRejectCreditCards(false)
            ->setRejectDebitCards(false)
            ->setRejectConsumerCards(false)
            ->setRejectCorporateCards(false)
            ->setRejectAuthenticationStatusA(false)
            ->setRejectAuthenticationStatusU(false);

        $payment = new PaymentPurchase();
        $payment->setOperation('Purchase')
            ->setIntent('AutoCapture')
            ->setCurrency('SEK')
            ->setGenerateRecurrenceToken(true)
            ->setDescription('Faktura #' . $invoiceId)
            ->setUserAgent('Mozilla/5.0...')
            ->setLanguage('sv-SE')
            ->setPayerReference($customer['userid'])
            ->setUrls($url)
            ->setPayeeInfo($payeeInfo)
            ->setPrices($prices)
            ->setCardholder([
            	'firstname' => $customer['firstname'],
            	'lastname' => $customer['lastname'],
            	'email' => $customer['email']
            ]);

        $paymentObject = new PaymentPurchaseObject();
        $paymentObject->setPayment($payment);
        $paymentObject->setCreditCard($creditCard);

        $this->purchaseRequest = new Purchase($paymentObject);
        $this->purchaseRequest->setClient($this->client);`

Easy to fill in when you know what objects to use, but hard for a new user.
So I would prefer some simplicity (it could absolutely be me missing things in documentation/test)

**Comment by aait** [comment]
@mattiashallstrom Hello, we have updated classes there https://github.com/SwedbankPay/swedbank-pay-sdk-php/pull/60

**Comment by mattiashallstrom** [comment]
Looks great!
