### ISSUE TITLE
Feature Request: Direct bank transfer payments via Trustly 

### ISSUE THREAD

**Issue by samface** [SwedbankPay/swedbank-pay-sdk-php#32]
Currently this SDK doesn't seem to have support for Trustly payments as described here:
https://developer.swedbankpay.com/payments/trustly/

Is this something in progress and in what time frame could one expect this to be implemented?

**Comment by asbjornu** [comment]
We have this in our backlog, but currently other features have higher priority so I can't say when this will be implemented. We are happy to accept pull requests, though.

**Comment by samface** [comment]
@asbjornu This should probably be communicated a bit clearer when advertising and selling your payment service. My employer was told that direct bank transfers was supported, even though he told the seller that we have magento2 and want the integrated swedbank pay payments solution rather than the checkout. Of course this is not to blame you as developers for, but please do feel free to forward this to your sales department.

**Comment by asbjornu** [comment]
@samface, were you told that direct bank transfer was explicitly supported in the PHP SDK?

**Comment by samface** [comment]
@asbjornu to have direct bank transfers as a payment option was a criteria for choosing swedbank pay as payment provider for our magneto2 based e-commerce and this was promised. we're obviously not getting it in the foreseeable future and will therefore have to re-evaluate our choice of payment provider.

**Comment by asbjornu** [comment]
What exactly was promised? We do have support for Trustly as a PSP, we just haven't implemented it in all of our SDKs and plugins yet, as the service has only been in production for a couple of weeks.

**Comment by samface** [comment]
@asbjornu I think I have been as exact as I can be with regards to what was promised. It was a verbal promise made over a year ago, at a time when there was a completely different PayEx PHP library as well as module for M2, and apparently the person who made the promise it isn't even working for you anymore. The details are however not important as I'm not bringing this up for playing the blame game or anything like that. I just thought it would be a good idea for you to be clear about this when advertising and selling your service as it obviously wasn't clear enough in this case.

For me this is sad as it means I most likely won't be able to use the implementation I myself have taken a big part in developing. Maybe we can consider it again some time in the future, but it won't be easy to convince my boss to change back once we've gone down another route.

**Comment by asbjornu** [comment]
Thanks for your feedback. We have routines in place now to ensure our sellers are better informed of our products and their capabilities, including SDKs and modules.

What happened over a year ago is very hard for me to do anything about now. The PHP library and M2 integration we had back then was based on our legacy POPS platform that was more mature and had more functionality just due to its age. However, the entire POPS platform is now being phased out, as I'm sure you're aware of. There's absolutely nothing I can do about that, I'm afraid.

**Comment by asbjornu** [comment]
Trustly was implemented in #36. Closing as completed.
