### ISSUE TITLE
AbstractSimpleDataObject implements ArrayAccess but doesn't follow it's signatures

### ISSUE THREAD

**Issue by letharion** [SwedbankPay/swedbank-pay-sdk-php#95]
AbstractSimpleDataObject override the signature of ArrayAccess, which causes warnings.

https://www.php.net/manual/en/class.arrayaccess.php

If it was just about adding the return values I would provide a PR, but fixing this isn't entirely trivial since it looks like AbstractSimpleDataObject wants to have a fluent interface, which ArrayAccess doesn't really support.

**Comment by letharion** [comment]
Here's a simplified example, which replicates the important part of AbstractSimpleDataObject

```
class ArrayAccessOverride implements ArrayAccess {
  function offsetExists($offset): bool {
  }
  function offsetGet($offset): mixed {
  }
  function offsetSet($offset, $value): ArrayAccessOverride {
    return $this;
  }
  function offsetUnset($offset): ArrayAccessOverride {
    return $this;
  }
}
```

The code _says_ that it `implements ArrayAccess`, but in practice it does not, because it returns `$this` when from two functions where the interface specifies it should return `void`.

The interface mismatch leads to this deprecation warning:

> PHP Deprecated:  Return type of ArrayAccessOverride::offsetSet($offset, $value): ArrayAccessOverride should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /tmp/array/a.php on line 8
> 
> Deprecated: Return type of ArrayAccessOverride::offsetSet($offset, $value): ArrayAccessOverride should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /tmp/array/a.php on line 8
> PHP Deprecated:  Return type of ArrayAccessOverride::offsetUnset($offset): ArrayAccessOverride should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /tmp/array/a.php on line 11
> 
> Deprecated: Return type of ArrayAccessOverride::offsetUnset($offset): ArrayAccessOverride should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /tmp/array/a.php on line 11

Presumably this will work until PHP 9 is released when the deprecation will likely become unsupported.

**Comment by olegisk** [comment]
@letharion ah, you mean PHP 8.1. It is not supported yet.
But thanks for reporting. We will take a look at that and will fix
